CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL
);

CREATE TABLE order_item (
    order_id BIGINT NOT NULL,
    orders_key INT NOT NULL,
    product VARCHAR(255) NOT NULL,
    quantity INT NOT NULL
);
